# Generated by Django 5.2 on 2025-04-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
