# Generated by Django 5.2 on 2025-04-06 11:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advert', '0002_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
