# Generated by Django 5.2 on 2025-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advert', '0003_alter_advertisement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, null=True),
        ),
    ]
