# Generated by Django 5.2 on 2025-04-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advert', '0004_alter_media_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
